### PR TITLE
Move vue to peerDependency

### PR DESCRIPTION
**Pull request by ctf0**

### CODE REVIEW

**Comment by Inndy** [comment]
You should write more detail in commit log like "Move vue to peerDependency", then force push to overwrite your PR.

**Comment by Inndy** [comment]
@ctf0 Read this: https://git-scm.com/book/zh-tw/v2/Git-Tools-Rewriting-History then merge them into one commit

**Comment by ctf0** [comment]
better ?

**Comment by Inndy** [comment]
LGTM, thanks for the PR!

**Pull request merged**
